import { useEffect, useState } from "react";
import { MessageSquare, Phone, PhoneOff } from "lucide-react";
import { usePrivia } from "./store";
import { channelCopy, nowISO, outreachBlocker, uid } from "./model";
import { Action, Card, Eyebrow, inputClass, Note, TextLink } from "./ui";

export function DemoControls() {
  const { state, commit, privateEdit, setSurface, setChatOpen, setNotice, sms, send, stop, isPending, reset, exportSnapshot, setCallVerified } = usePrivia();
  const [mode, setMode] = useState<"controls" | "sms" | "call">("controls");
  const [privateCall, setPrivateCallState] = useState<boolean>(false);
  const setPrivateCall = (value: boolean) => { setPrivateCallState(value); setCallVerified(value); };
  const [callStarted, setCallStarted] = useState<boolean>(false);
  useEffect(() => () => stop(), [stop]);
  useEffect(() => { if (!state.channel.call || state.channel.stopped) { setPrivateCallState(false); setCallStarted(false); } }, [state.channel.call, state.channel.stopped]);
  const invite = (channel: "sms" | "call") => {
    const now = new Date(); const blocker = outreachBlocker(state, channel, now);
    if (blocker) { setNotice(blocker); return; }
    if (commit(s => { s.channel.lastOutreach = now.toISOString(); s.turns.push({ id: uid(), role: "assistant", channel, text: channel === "sms" ? channelCopy.invite : channelCopy.call, at: nowISO(), status: "complete", origin: "sample-channel", dismissed: false }); })) { setMode(channel); if (channel === "call") setCallStarted(true); }
  };
  const returnToApp = () => { setPrivateCall(false); stop(); setSurface(null); setChatOpen(true); };
  return <><div className="flex gap-2">{([ ["controls", "Scenario"], ["sms", "SMS preview"], ["call", "Call preview"] ] as const).map(([id, label]) => <Action key={id} className="flex-1 px-2 text-xs" secondary={mode !== id} onClick={() => { stop(); setPrivateCall(false); setMode(id); }}>{label}</Action>)}</div>
    {mode === "controls" && <><Card><Eyebrow>Elena · 52 · synthetic patient</Eyebrow><p className="my-3 text-sm leading-relaxed">Type 2 diabetes and high blood pressure. No real accounts, patient data, orders or messages. Sample stage changes are explicit and never performed by AI.</p><label className="flex min-h-12 items-center gap-3 text-sm"><input type="checkbox" className="h-5 w-5 accent-[#287d66]" checked={state.orderAvailable} onChange={e => privateEdit(s => { s.orderAvailable = e.target.checked; })} />Stage a clinician-approved sample order</label><label className="flex min-h-12 items-center gap-3 text-sm"><input type="checkbox" className="h-5 w-5 accent-[#287d66]" checked={state.practiceReply} onChange={e => privateEdit(s => { s.practiceReply = e.target.checked; })} />Stage a sample practice response</label><label className="flex min-h-12 items-center gap-3 text-sm"><input type="checkbox" className="h-5 w-5 accent-[#287d66]" checked={state.stage === "after"} onChange={e => privateEdit(s => { s.stage = e.target.checked ? "after" : "before"; })} />Advance to after the sample visit</label></Card>
      <Card><Eyebrow>Illustrative conversation starters</Eyebrow><Note>These are examples, not inferred patient concerns. Selecting one puts it in the composer for review; nothing is sent.</Note>{["I keep putting off the blood test.", "I felt faint at my last blood draw. I don’t want that to happen again.", "Keep it practical. Can you find the lab details and compare times?", "I haven’t managed the routine we discussed. Can we make the practical part smaller?"].map(text => <button className="min-h-14 w-full border-b border-[#00211a]/10 py-3 text-left text-sm" key={text} onClick={() => { if (state.composer && !window.confirm("Replace your current unsent question?")) return; if (commit(s => { s.composer = text; })) { setSurface(null); setChatOpen(true); } }}>{text}</button>)}</Card>
      <ChannelPreferences /><Action secondary onClick={exportSnapshot}>Export Elena’s demo snapshot</Action><TextLink onClick={() => { if (window.confirm("Reset only Elena’s demo? Export first if you want to keep this work.")) reset(); }}>Reset this demo</TextLink><a className="block min-h-11 py-3 text-sm underline" href="/legacy">Open earlier scenarios separately</a><Note>Earlier scenarios retain their original patients and saved work. They contain legacy prototype behavior and do not share this workspace.</Note></>}
    {mode === "sms" && <><Card><div className="flex items-center gap-3"><MessageSquare size={20} /><div><Eyebrow>SMS · interactive simulation</Eyebrow><p className="mt-1 text-sm">No phone number or live SMS service</p></div></div><div className="my-4 max-h-80 space-y-3 overflow-y-auto">{state.turns.filter(t => t.channel === "sms").map(t => <p key={t.id} className={`whitespace-pre-wrap rounded-2xl p-3 text-sm leading-relaxed ${t.role === "user" ? "ml-6 bg-[#dfefe6]" : "mr-6 bg-[#f1f3ef]"}`}>{t.text}</p>)}{!state.turns.some(t => t.channel === "sms") && <Note>No preview messages yet.</Note>}</div><form className="space-y-3" onSubmit={e => { e.preventDefault(); sms(state.channel.smsDraft); }}><label className="block space-y-2 text-sm"><span>Sample incoming text</span><textarea className={inputClass} value={state.channel.smsDraft} maxLength={2000} onChange={e => commit(s => { s.channel.smsDraft = e.target.value; })} placeholder="BP 138/84 2026-09-17 08:00" /></label><Action type="submit" disabled={!state.channel.smsDraft.trim()}>Submit sample reply</Action></form><TextLink onClick={returnToApp}>Open app · continue the same thread</TextLink></Card><Note>Incoming values are recorded only with an explicit pair, date and time. Ambiguous values are not saved. Outbound acknowledgments never repeat health details. Correct an entry in Your logs.</Note><Action secondary onClick={() => invite("sms")}>Preview an optional invitation</Action><ChannelPreferences /></>}
    {mode === "call" && <><Card><div className="flex items-center gap-3"><Phone size={20} /><Eyebrow>Telephone · transcript simulation</Eyebrow></div><p className="my-4 text-sm leading-relaxed">{channelCopy.call}</p><Note>No real call or recording. These self-confirmation controls demonstrate a boundary, not production identity verification.</Note>{!callStarted ? <Action className="mt-4" onClick={() => invite("call")}>Start sample call</Action> : !privateCall ? <div className="mt-4 space-y-3"><Action className="w-full" onClick={() => setPrivateCall(true)}>Simulate identity verified · private moment</Action><Action secondary className="w-full" onClick={returnToApp}>Not private · return to the app</Action></div> : <><div className="my-4 max-h-64 space-y-4 overflow-y-auto">{state.turns.filter(t => t.channel === "call" && t.origin !== "sample-channel").map(t => <div key={t.id}><Eyebrow>{t.role === "user" ? "You" : "Rumi · AI"}</Eyebrow><p className="mt-1 whitespace-pre-wrap text-sm leading-relaxed">{t.text}</p></div>)}</div>{!state.aiConsent && <Action secondary onClick={() => privateEdit(s => { s.aiConsent = true; })}>Enable temporary AI for synthetic call transcript</Action>}<form className="mt-3 space-y-3" onSubmit={e => { e.preventDefault(); send(state.channel.callDraft, "call"); }}><label className="block space-y-2 text-sm"><span>Your side of the call</span><textarea className={inputClass} value={state.channel.callDraft} onChange={e => commit(s => { s.channel.callDraft = e.target.value; })} /></label><Action disabled={isPending || !state.aiConsent || !state.channel.callDraft.trim()}>Continue transcript</Action></form>{isPending && <Action secondary className="mt-3" onClick={stop}>Interrupt reply</Action>}<TextLink onClick={returnToApp}>Continue privately in the app</TextLink></>}<Action secondary className="mt-4" onClick={() => { stop(); setPrivateCall(false); setCallStarted(false); }}><PhoneOff size={16} />End sample call</Action></Card><Note>Voicemail preview: “This is Rumi. Please open the app when convenient.” No personal or health details. Apple Messages for Business is a separate future integration—not consumer iMessage access.</Note><ChannelPreferences /></>}
  </>;
}
function ChannelPreferences() {
  const { state, privateEdit } = usePrivia();
  return <Card><Eyebrow>Preview outreach preferences</Eyebrow>{(["sms", "call"] as const).map(c => <label className="mt-3 flex min-h-11 items-center gap-3 text-sm" key={c}><input type="checkbox" className="h-5 w-5 accent-[#287d66]" checked={state.channel[c]} onChange={e => privateEdit(s => { s.channel[c] = e.target.checked; if (e.target.checked) s.channel.stopped = false; })} />Allow optional {c === "sms" ? "text" : "call"} preview invitations</label>)}<div className="mt-3 grid grid-cols-2 gap-3">{([ ["quietStart", "Quiet from"], ["quietEnd", "Until"] ] as const).map(([key, label]) => <label key={key} className="space-y-2 text-sm"><span>{label} · Eastern</span><select className={inputClass} value={state.channel[key]} onChange={e => privateEdit(s => { s.channel[key] = Number(e.target.value); })}>{Array.from({ length: 24 }, (_, h) => <option key={h} value={h}>{String(h).padStart(2, "0")}:00</option>)}</select></label>)}</div><p className="mt-3 text-xs leading-relaxed text-[#53685f]">Preview policy: at most one invitation in 24 hours across both channels, never during quiet hours or a pause. This illustrative limit is not approved production policy. No background outreach exists.</p></Card>;
}
