import { useEffect, type ReactNode } from "react";
import { NavLink, Route, Routes, useLocation } from "react-router-dom";
import { ArrowRight, BookOpen, CalendarDays, FileText, Heart, Home, Leaf, MessageCircle, Plus, Settings2, ShieldCheck, UserRound, X } from "lucide-react";
import NotFound from "../pages/NotFound";
import { usePrivia } from "./store";
import { DEMO_ENABLED, formatVisit } from "./model";
import { Action, Card, Eyebrow, Note, Row, RumiMark, Sheet, TextLink, Title } from "./ui";
import { Connections, EvidenceList, GuideWorkspace, LabWorkspace, MessageWorkspace, VisitWorkspace } from "./Workspaces";
import { LogForm, Logs, Preferences, Support } from "./Personal";
import { Conversation } from "./Conversation";
import { DemoControls } from "./DemoControls";
import "./privia.css";

export function DemoUnavailable() { return <main className="privia grid min-h-dvh place-content-center bg-[#f6f9f4] px-6 text-center"><h1 className="font-fields text-4xl">Demo disabled</h1><p className="mx-auto mt-4 max-w-md text-sm leading-relaxed">Real patient access has not been implemented. No sample workspace or external action is available in this build.</p></main>; }
export function PriviaApp() {
  const s = usePrivia(); const location = useLocation();
  useEffect(() => { document.title = "Rumi · Privia Health demo"; document.documentElement.classList.remove("night", "day"); }, []);
  const { setSurface } = s;
  useEffect(() => { setSurface(null); }, [location.pathname, setSurface]); // Direct navigation never resets the shared workspace.
  if (!DEMO_ENABLED) return <DemoUnavailable />;
  const titles: Record<string, string> = { connections: "Your sample sources", lab: "Plan the lab step", guide: "Your visit guide", message: "Practice message", support: "Your personal plan", records: "Records & evidence", logs: "Your logs", preferences: "Memory & preferences", visit: "Your appointment", demo: "Demonstration controls" };
  const content: Record<string, ReactNode> = { connections: <Connections />, lab: <LabWorkspace />, guide: <GuideWorkspace />, message: <MessageWorkspace />, support: <Support />, records: <EvidenceList />, logs: <Logs />, preferences: <Preferences />, visit: <VisitWorkspace />, demo: <DemoControls /> };
  return <div className="privia privia-wash flex min-h-dvh w-full items-center justify-center lg:gap-20">
    <aside className="hidden w-64 space-y-6 lg:block"><div className="flex items-center gap-3"><RumiMark className="h-11 w-11" /><span className="font-fields text-4xl">Rumi</span></div><h2 className="font-fields text-[32px] leading-tight">Care, at your pace.</h2><p className="text-sm leading-relaxed text-[#53685f]">A continuing care experience, with practical help when it’s wanted.</p><div className="border-t border-[#00211a]/15 pt-5"><Eyebrow>Privia Health demo</Eyebrow><p className="mt-3 text-xs leading-relaxed text-[#53685f]">Synthetic patient and sample services. Not endorsed by or connected to Privia Health.</p></div><Action secondary onClick={() => s.setSurface("demo")}>Explore the demonstration</Action></aside>
    <div data-testid="privia-device" className="privia-wash relative h-dvh w-full max-w-[460px] overflow-hidden shadow-[0_20px_100px_-40px_#16483d66] lg:my-5 lg:h-[min(900px,calc(100dvh-40px))] lg:rounded-[38px] lg:border lg:border-white">
      <div aria-hidden="true" className="privia-texture pointer-events-none absolute inset-0 opacity-25" />
      <header aria-hidden={s.chatOpen} data-chrome className="relative flex items-center justify-between px-6 pb-4 pt-[max(22px,env(safe-area-inset-top))]"><div className="flex items-center gap-2"><RumiMark className="h-7 w-7" /><span className="font-fields text-2xl tracking-tight">Rumi</span></div><button className="min-h-11 rounded-full border border-[#00211a]/10 bg-white/50 px-3 text-[10px] font-medium tracking-wide" onClick={() => s.setSurface("demo")}>PRIVIA HEALTH DEMO</button></header>
      <main aria-hidden={s.chatOpen} className="absolute inset-x-0 bottom-0 top-[88px] overflow-y-auto px-6 pb-48" key={location.pathname}>
        {s.error && <Card className="mb-5 border-[#a5532c]" ><p className="text-sm" role="alert">{s.error}</p><div className="mt-3 flex flex-wrap gap-2"><Action secondary onClick={s.exportSnapshot}>Export saved work</Action><Action secondary onClick={() => window.location.reload()}>Reload</Action><Action secondary onClick={() => s.setSurface("demo")}>Recovery controls</Action></div></Card>}
        <Routes><Route path="/" element={<Today />} /><Route path="/care" element={<Care />} /><Route path="/messages" element={<Messages />} /><Route path="/you" element={<You />} /><Route path="*" element={<NotFound />} /></Routes>
      </main>
      {!s.chatOpen && <><button data-chrome onClick={() => s.openChat()} aria-label="Talk with Rumi" className="absolute bottom-[112px] right-6 flex min-h-12 items-center gap-2 rounded-full border border-white bg-[#fffefa]/95 px-4 py-2 shadow-[0_4px_24px_#16483d1a] backdrop-blur-xl"><RumiMark busy={s.isPending} className="h-7 w-7" /><span className="text-sm font-medium">Rumi</span></button><nav aria-label="Main navigation" className="absolute bottom-4 left-3 right-3 grid grid-cols-5 items-center rounded-[28px] border border-white/90 bg-[#fffefa]/90 px-2 pb-[max(8px,env(safe-area-inset-bottom))] pt-2 shadow-[0_4px_30px_#16483d15] backdrop-blur-2xl"><Tab to="/" label="Today" icon={<Home size={21} />} /><Tab to="/care" label="Care" icon={<Heart size={21} />} /><button aria-label="Log" onClick={() => s.setLogOpen(true)} className="flex min-h-16 flex-col items-center justify-center gap-1"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#00211a] text-white"><Plus size={23} /></span><span className="text-[10px] font-medium">Log</span></button><Tab to="/messages" label="Messages" icon={<MessageCircle size={21} />} /><Tab to="/you" label="You" icon={<UserRound size={21} />} /></nav></>}
      {s.chatOpen && <Conversation />}
      {s.notice && !s.chatOpen && !s.surface && !s.logOpen && <div className="absolute inset-x-5 bottom-[175px] z-40 flex items-center gap-2 rounded-2xl border border-[#bed7c9] bg-[#fffefa] p-4 shadow-md"><p className="flex-1 text-sm" role="status">{s.notice}</p><button aria-label="Dismiss notice" className="h-11 w-11 shrink-0" onClick={() => s.setNotice(null)}><X size={17} /></button></div>}
    </div>
    <Sheet open={!!s.surface} onClose={() => s.setSurface(null)} title={titles[s.surface ?? ""] ?? "Rumi"}>{s.notice && <div className="flex items-start gap-2 rounded-xl bg-[#dfeee5] p-3"><p className="flex-1 text-sm" role="status">{s.notice}</p><button className="h-11 w-11 shrink-0" aria-label="Dismiss notice" onClick={() => s.setNotice(null)}><X size={16} /></button></div>}{s.surface && content[s.surface]}</Sheet>
    <Sheet open={s.logOpen} onClose={() => s.setLogOpen(false)} title={s.state.logDraft.editingId ? "Correct your entry" : "Log something"} description="A quick entry. No conversation needed."><LogForm key={`${s.logOpen}-${s.state.logDraft.editingId}`} /></Sheet>
  </div>;
}
function Tab({ to, label, icon }: { to: string; label: string; icon: ReactNode }) { return <NavLink end to={to} className={({ isActive }) => `flex min-h-16 flex-col items-center justify-center gap-1.5 rounded-2xl text-[10px] ${isActive ? "bg-[#e7f2eb] font-semibold text-[#00211a]" : "text-[#65766c]"}`}>{icon}{label}</NavLink>; }
function Today() {
  const { state, setSurface, openChat } = usePrivia();
  const isAfter = state.stage === "after";
  const lastMessage = state.turns.filter(t => t.role === "user").at(-1);
  return <div className="space-y-5"><div className="pb-3 pt-2"><Eyebrow>{isAfter ? "After the sample visit" : "Thursday, September 17"}</Eyebrow><h1 className="mt-3 font-fields text-[40px] leading-[1.08] tracking-[-0.035em]">Hello, Elena.</h1><p className="mt-3 text-[15px] leading-relaxed text-[#53685f]">{lastMessage ? "Your conversation is here when you’re ready." : "What would help today?"}</p></div>
    <Card className="relative overflow-hidden !p-0"><div className="flex items-center gap-2 border-b border-[#00211a]/5 bg-[#e8f3ec] px-5 py-3"><CalendarDays size={15} /><span className="text-[11px] font-medium">{isAfter ? "Following your visit" : "Your next visit"}</span><span className="ml-auto text-[11px] text-[#53685f]">{formatVisit(state.visit.at)} ET</span></div><div className="p-5"><h2 className="font-fields text-[29px] leading-tight">{isAfter ? "Make the plan work\nfor you" : "A visit with your\nquestions in it"}</h2><p className="mb-5 mt-3 text-[14px] leading-relaxed text-[#53685f]">{isAfter ? "Choose a practical next step, adjust the support, or leave it for now." : state.guide.questions.length ? `${state.guide.questions.length} question${state.guide.questions.length > 1 ? "s" : ""} saved. You can add to them as things come up.` : "There’s time to gather what you want to ask and work through the next step."}</p><Action className="w-full justify-between" onClick={() => setSurface(isAfter ? "support" : "guide")}>{isAfter ? "Your personal plan" : "Prepare in your own words"}<ArrowRight size={18} /></Action><button className="mt-1 flex min-h-11 w-full items-center justify-center text-[13px]" onClick={() => setSurface(isAfter ? "records" : "visit")}>{isAfter ? "Read the sample care plan" : "Appointment details"}</button></div></Card>
    <Card><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#f8e3db]"><RumiMark className="h-6 w-6" /></span><Eyebrow>{lastMessage ? "Continue with Rumi" : "Before the visit"}</Eyebrow></div><h2 className="mt-4 font-fields text-[25px] leading-tight">{lastMessage ? "Pick up where you left off" : "Something making it harder?"}</h2><p className="mt-3 line-clamp-3 text-[14px] leading-relaxed text-[#53685f]">{lastMessage ? lastMessage.text : "We can talk it through. Or just find the practical detail you need."}</p><TextLink onClick={() => openChat()}>{lastMessage ? "Continue conversation" : "Talk with Rumi"}</TextLink></Card>
    {state.support.goal && !state.support.paused && <Card><Eyebrow>Your chosen step{state.support.reminder ? ` · ${state.support.reminder}` : ""}</Eyebrow><p className="my-3 text-sm">{state.support.goal}</p><TextLink onClick={() => setSurface("support")}>Adjust or check in</TextLink></Card>}
    <button className="flex min-h-14 w-full items-center justify-between gap-3 rounded-2xl border border-white/80 bg-white/50 px-4 text-left text-[13px]" onClick={() => setSurface(state.calendarEvents.length ? "lab" : "logs")}><span>{state.calendarEvents.length ? "Your saved sample lab plan" : `${state.logs.length} saved observation${state.logs.length === 1 ? "" : "s"}`}</span><ArrowRight size={16} /></button>
  </div>;
}
function Care() {
  const { setSurface } = usePrivia();
  return <div className="space-y-5 pt-3"><Title>Your care</Title><Note>Your details, questions and plans, together.</Note><Card><Row title="Appointments" detail="Your visit and preparation" icon={<CalendarDays size={21} />} onClick={() => setSurface("visit")} /><Row title="Care plan" detail="A step that fits your day" icon={<Leaf size={21} />} onClick={() => setSurface("support")} /><Row title="Meds & refills" detail="No verified medication list in this sample" icon={<Heart size={21} />} onClick={() => setSurface("records")} /><Row title="Records & results" detail="Sources and selected observations" icon={<FileText size={21} />} onClick={() => setSurface("records")} /></Card><Card><Eyebrow>Before your visit</Eyebrow><Row title="Lab preparation" detail="Order status, evidence and a calendar plan" onClick={() => setSurface("lab")} /><Row title="Discussion guide" detail="Your questions, not someone else’s agenda" onClick={() => setSurface("guide")} /></Card><TextLink onClick={() => setSurface("connections")}>Manage sample connections</TextLink></div>;
}
function Messages() {
  const { state, setSurface, openChat } = usePrivia();
  return <div className="space-y-5 pt-3"><Title>Messages</Title><Note>Practice drafts are separate from your conversation with Rumi.</Note><Card><Row title="Sample primary care team" detail={state.lab.message ? "Unfinished draft · pick up here" : "Ask a question or review a draft"} icon={<MessageCircle size={21} />} onClick={() => setSurface("message")} />{state.practiceReply && <p className="mt-3 rounded-xl bg-[#edf5ef] p-3 text-sm">Staged practice response available. No real practice has replied.</p>}</Card>{state.messages.map(m => <Card key={m.id}><Eyebrow>{m.status}</Eyebrow><p className="my-2 font-medium">{m.recipient}</p><p className="whitespace-pre-wrap text-sm leading-relaxed">{m.text}</p></Card>)}<Card><Row title="Your conversation with Rumi" detail={`${state.turns.length} saved turns · app and channel previews`} icon={<RumiMark className="h-7 w-7" />} onClick={() => openChat()} /></Card><Note>Not monitored for urgent needs. No messages leave this demonstration.</Note></div>;
}
function You() {
  const { state, setSurface } = usePrivia();
  return <div className="space-y-5 pt-3"><div className="flex items-center gap-4"><span className="grid h-16 w-16 place-items-center rounded-full border border-white bg-[#e4efe4] font-fields text-3xl">E</span><div><Title>Elena</Title><Note>52 · synthetic demo patient</Note></div></div><Card><Row title="Your logs" detail={`${state.logs.length} entries · view, correct or remove`} icon={<BookOpen size={21} />} onClick={() => setSurface("logs")} /><Row title="Memory & preferences" detail="What Rumi remembers, and how it helps" icon={<Settings2 size={21} />} onClick={() => setSurface("preferences")} /><Row title="Your personal plan" detail={state.support.goal || "Optional support, at your pace"} icon={<Leaf size={21} />} onClick={() => setSurface("support")} /><Row title="Connections & privacy" detail="Choose the sample information Rumi can use" icon={<ShieldCheck size={21} />} onClick={() => setSurface("connections")} /></Card><TextLink onClick={() => setSurface("demo")}>Demonstration controls & channel previews</TextLink><Note>Saved only in this browser. Not a verified patient account or cross-device record. Earlier scenarios and the broader feature library remain separate.</Note></div>;
}
