import { useMemo, useState } from "react";
import { ArrowDown, ArrowUp, CalendarDays, Check, FileText, Trash2 } from "lucide-react";
import { usePrivia } from "./store";
import { applyLab, applyMessage, busyEvents, evidence, formatVisit, guideFingerprint, labBlocker, labFingerprint, messageFingerprint, overlaps, slots, uid } from "./model";
import { Action, Card, Eyebrow, inputClass, Note, Row, TextLink } from "./ui";

export function Connections() {
  const { state, privateEdit } = usePrivia();
  return <><Note>Choose what Rumi may use. These are sample sources, not Google authorization or a medical-record connection.</Note>{([ ["gmail", "Sample Gmail", "Search sample logistics emails and inspect the originals."], ["calendar", "Sample Google Calendar", "Compare existing commitments and save private-title sample events."], ["records", "Sample care information", "Use Elena’s synthetic visit, order and selected observations."] ] as const).map(([key, title, detail]) => <Card key={key}><label className="flex min-h-11 items-start gap-4"><span className="flex-1"><span className="block font-medium">{title}</span><span className="mt-1 block text-[13px] text-[#53685f]">{detail}</span></span><input type="checkbox" className="mt-1 h-6 w-6 accent-[#287d66]" checked={state.sources[key]} onChange={e => privateEdit(s => { s.sources[key] = e.target.checked; })} /></label></Card>)}<Note>Removing a source stops active AI work, excludes previous conversation history from future AI requests and invalidates approvals. Saved drafts remain visible to you. Nothing connects to a real account.</Note></>;
}

export function EvidenceList({ gmailOnly = false }: { gmailOnly?: boolean }) {
  const { state, setSurface, openChat } = usePrivia();
  const [query, setQuery] = useState<string>("");
  const found = useMemo(() => evidence(state).filter(e => (!gmailOnly || e.source === "gmail") && state.sources[e.source] && `${e.title} ${e.body}`.toLowerCase().includes(query.toLowerCase())), [state, gmailOnly, query]);
  return <><label className="block space-y-2 text-sm"><span>Search {gmailOnly ? "sample inbox" : "available evidence"}</span><input className={inputClass} type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Try “lab” or “preparation”" /></label>{found.map(e => <Card key={e.id}><Eyebrow>{e.source === "gmail" ? "Sample Gmail" : "Sample record"} · {formatVisit(e.date)} ET</Eyebrow><details className="mt-2"><summary className="min-h-11 cursor-pointer py-2 font-medium">{e.title}</summary><p className="whitespace-pre-wrap py-3 text-[14px] leading-relaxed">{e.body}</p><TextLink onClick={() => { setSurface(null); openChat(e.id); }}>Ask Rumi with this source</TextLink></details></Card>)}{!found.length && <Card><p>No matching permitted sources.</p><TextLink onClick={() => setSurface("connections")}>Choose sample sources</TextLink></Card>}</>;
}

export function LabWorkspace() {
  const { state, commit, setSurface, setNotice } = usePrivia();
  const [expanded, setExpanded] = useState<boolean>(false);
  const blocker = labBlocker(state);
  const reviewed = state.lab.approval === labFingerprint(state);
  const shown = state.preferences.pace === "detailed" || expanded ? slots : slots.filter(x => x.id === (state.lab.slot || "09:30"));
  const apply = () => {
    try { if (commit(s => Object.assign(s, applyLab(s)))) setNotice("Saved in the sample calendar. The lab draw is not booked."); }
    catch (e) { setNotice(e instanceof Error ? e.message : "The plan could not be saved."); }
  };
  return <><Card><Eyebrow>For your visit · {formatVisit(state.visit.at)} ET</Eyebrow><h2 className="mt-2 font-fields text-2xl">Before the blood draw</h2><p className="mt-3 text-sm leading-relaxed">{state.orderAvailable ? "A clinician-approved order is present in this staged sample. Preparation instructions still need confirmation." : "The order has not been confirmed. The next step can be a question to the practice—not a booking."}</p><TextLink onClick={() => setSurface("message")}>Prepare a question to the practice</TextLink></Card>
    <details><summary className="min-h-11 cursor-pointer py-3 font-medium">View source emails and instructions</summary><div className="space-y-4 pt-2"><EvidenceList gmailOnly /></div></details>
    {state.orderAvailable && <><div><Eyebrow>September 23 · Eastern time</Eyebrow><h2 className="mt-1 font-fields text-2xl">A time that fits</h2><Note>Planning options only. No travel allowance is included.</Note></div>{!state.sources.calendar || !state.sources.records ? <Card><p>Choose Calendar and care information to compare times.</p><TextLink onClick={() => setSurface("connections")}>Choose sample sources</TextLink></Card> : <><div className="space-y-3">{shown.map(slot => {
      const conflict = [...busyEvents, ...state.calendarEvents].some(e => overlaps(slot, e));
      return <button key={slot.id} aria-pressed={state.lab.slot === slot.id} disabled={conflict} onClick={() => commit(s => { s.lab.slot = slot.id; s.lab.approval = null; })} className={`flex min-h-20 w-full items-center gap-3 rounded-2xl border bg-white p-4 text-left ${state.lab.slot === slot.id ? "border-[#287d66] ring-1 ring-[#287d66]" : "border-[#00211a]/10"} disabled:opacity-60`}><CalendarDays size={20} /><span className="flex-1"><span className="block font-medium">{slot.label}</span><span className="text-xs text-[#53685f]">{conflict ? "Conflicts with an existing event" : "No overlap in the sample calendar"}</span></span>{state.lab.slot === slot.id && <Check size={18} />}</button>;
    })}</div>{!expanded && state.preferences.pace !== "detailed" && <TextLink onClick={() => setExpanded(true)}>Compare all three times</TextLink>}
    <Card><Eyebrow>Calendar review</Eyebrow><h3 className="my-2 font-medium">Personal appointment</h3><Note>Only this private title and the chosen time go into the sample calendar. No diagnosis, lab instructions, address or personal concern is included.</Note><div className="mt-4 flex flex-wrap gap-2"><Action secondary disabled={!!blocker} onClick={() => commit(s => { s.lab.approval = labFingerprint(s); })}>{reviewed ? "Reviewed" : "Review this event"}</Action><Action disabled={!reviewed || !!blocker} onClick={apply}>Save sample event</Action></div>{blocker && <p className="mt-3 text-xs text-[#725119]">{blocker}</p>}</Card></> }</>}
    {state.calendarEvents.map(event => <Card key={event.id}><Eyebrow>Saved sample event · not a booking</Eyebrow><p className="mt-2 font-medium">{formatVisit(event.start)} ET</p>{event.visitRevision !== state.visit.revision && <p className="mt-2 text-sm text-[#8a491b]">The visit changed. Review whether this event still fits.</p>}<TextLink onClick={() => commit(s => { s.calendarEvents = s.calendarEvents.filter(e => e.id !== event.id); s.lab.approval = null; })}>Remove sample event</TextLink></Card>)}
    <TextLink onClick={() => setSurface("guide")}>Continue to your visit questions</TextLink></>;
}

export function MessageWorkspace() {
  const { state, commit, setNotice, setSurface, openChat } = usePrivia();
  const approval = state.lab.messageApproval;
  const setApproval = (value: string | null) => commit(s => { s.lab.messageApproval = value; });
  const signature = messageFingerprint(state);
  const reviewed = approval === signature;
  const submit = () => {
    try { if (commit(s => Object.assign(s, applyMessage(s, approval ?? "")))) { setApproval(null); setNotice("Saved to sample messages. No real message was sent."); } }
    catch (e) { setNotice(e instanceof Error ? e.message : "The draft could not be saved."); }
  };
  return <><Note>This is a practice-message draft, not a Gmail email. Medical questions stay out of logistics email and calendar previews.</Note><label className="block space-y-2 text-sm"><span>Recipient</span><select className={inputClass} value={state.lab.recipient} onChange={e => commit(s => { s.lab.recipient = e.target.value; s.lab.approval = null; })}><option>Sample primary care team</option><option>Sample practice scheduling team</option></select></label><label className="block space-y-2 text-sm"><span>Message</span><textarea className={`${inputClass} min-h-44`} value={state.lab.message} maxLength={4000} placeholder="What would you like to ask?" onChange={e => commit(s => { s.lab.message = e.target.value; s.lab.approval = null; })} /></label><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" className="h-5 w-5 accent-[#287d66]" checked={state.lab.useEmail} onChange={e => commit(s => { s.lab.useEmail = e.target.checked; s.lab.approval = null; })} />Use the selected sample email as supporting evidence</label>{state.lab.useEmail && <Note>{state.sources.gmail ? "The sample email can inform your draft; it is not attached or forwarded." : "Sample Gmail is off. Remove this source or enable it before review."}</Note>}<Action secondary onClick={() => {
      if (state.lab.message && !window.confirm("Replace your current draft with this editable sample question?")) return;
      commit(s => { s.lab.message = "Could you confirm whether my lab order is ready and what preparation I need before the draw?"; });
    }}>Use a sample order question</Action>
    <TextLink onClick={() => { setSurface(null); openChat("message-draft"); }}>Ask Rumi with this draft</TextLink>
    <Action className="w-full" disabled={!state.lab.message.trim() || (state.lab.useEmail && !state.sources.gmail)} onClick={() => setApproval(signature)}>Review recipient and message</Action>{reviewed && <Card><Eyebrow>Review · nothing sent</Eyebrow><p className="mt-2 font-medium">To: {state.lab.recipient}</p><p className="my-4 whitespace-pre-wrap text-sm leading-relaxed">{state.lab.message}</p><Action className="w-full" onClick={submit}>Apply to sample messages</Action><Note>Simulated only. This does not reach a practice or establish receipt.</Note></Card>}{state.messages.map(m => <Card key={m.id}><Eyebrow>{m.status}</Eyebrow><p className="mt-2 text-sm font-medium">{m.recipient}</p><p className="mt-2 whitespace-pre-wrap text-sm">{m.text}</p></Card>)}</>;
}

export function GuideWorkspace() {
  const { state, commit, openChat, setSurface, setNotice } = usePrivia();
  const newQuestion = state.guide.draftQuestion;
  const setNewQuestion = (text: string) => commit(s => { s.guide.draftQuestion = text; });
  const [reviewing, setReviewing] = useState<boolean>(false);
  const reviewed = state.guide.reviewed === guideFingerprint(state);
  const exportGuide = () => {
    const content = `Rumi · Privia Health demo\nSynthetic patient: Elena, 52\nVisit: ${state.visit.id} · ${formatVisit(state.visit.at)} Eastern\nPatient-reviewed · not sent to an EHR\n\nQuestions\n${state.guide.questions.map((q, i) => `${i + 1}. ${q.text}`).join("\n")}\n\nSelected observations\n${state.logs.filter(l => state.guide.selectedLogIds.includes(l.id)).map(l => `${l.at} · ${l.kind}: ${l.value} · ${l.source}`).join("\n")}\n\n${state.guide.note}`;
    const url = URL.createObjectURL(new Blob([content], { type: "text/plain" })); const a = document.createElement("a"); a.href = url; a.download = "elena-visit-guide.txt"; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  return <><Card><Eyebrow>Your agenda · {formatVisit(state.visit.at)} ET</Eyebrow><h2 className="mt-2 font-fields text-2xl">What matters to you?</h2><Note>Questions belong to this visit. You can prepare everything here without using AI.</Note></Card>
    {state.guide.questions.map((q, index) => <Card key={q.id}><label className="block space-y-2 text-sm"><span>Question {index + 1}</span><textarea className={inputClass} value={q.text} maxLength={2000} onChange={e => commit(s => { s.guide.questions = s.guide.questions.map(x => x.id === q.id ? { ...x, text: e.target.value } : x); s.guide.reviewed = null; })} /></label><div className="flex justify-end gap-1"><button className="grid h-11 w-11 place-items-center disabled:opacity-30" aria-label={`Move question ${index + 1} up`} disabled={!index} onClick={() => commit(s => { const row = s.guide.questions.splice(index, 1)[0]; s.guide.questions.splice(index - 1, 0, row); s.guide.reviewed = null; })}><ArrowUp size={18} /></button><button className="grid h-11 w-11 place-items-center disabled:opacity-30" aria-label={`Move question ${index + 1} down`} disabled={index === state.guide.questions.length - 1} onClick={() => commit(s => { const row = s.guide.questions.splice(index, 1)[0]; s.guide.questions.splice(index + 1, 0, row); s.guide.reviewed = null; })}><ArrowDown size={18} /></button><button className="grid h-11 w-11 place-items-center" aria-label={`Remove question ${index + 1}`} onClick={() => commit(s => { s.guide.questions = s.guide.questions.filter(x => x.id !== q.id); s.guide.reviewed = null; })}><Trash2 size={17} /></button></div></Card>)}
    <form className="space-y-3" onSubmit={e => { e.preventDefault(); if (!newQuestion.trim()) return; if (commit(s => { s.guide.questions.push({ id: uid(), text: newQuestion.trim() }); s.guide.reviewed = null; })) setNewQuestion(""); }}><label className="block space-y-2 text-sm"><span>Add a question</span><input className={inputClass} value={newQuestion} maxLength={2000} onChange={e => setNewQuestion(e.target.value)} placeholder="Something you want to discuss" /></label><Action secondary type="submit" disabled={!newQuestion.trim()}>Add to this visit</Action></form>
    <details><summary className="min-h-11 cursor-pointer py-3 font-medium">Choose observations ({state.guide.selectedLogIds.length})</summary>{state.logs.map(l => <label key={l.id} className="flex min-h-16 items-center gap-3 border-b border-[#00211a]/10 py-3 text-sm"><input type="checkbox" className="h-5 w-5 accent-[#287d66]" checked={state.guide.selectedLogIds.includes(l.id)} onChange={e => commit(s => { s.guide.selectedLogIds = e.target.checked ? [...s.guide.selectedLogIds, l.id] : s.guide.selectedLogIds.filter(id => id !== l.id); s.guide.reviewed = null; })} /><span>{l.kind}: {l.value}<span className="block text-xs text-[#53685f]">{l.at.replace("T", " · ")} · {l.source}</span></span></label>)}</details>
    <label className="block space-y-2 text-sm"><span>Anything else for this visit</span><textarea className={inputClass} value={state.guide.note} onChange={e => commit(s => { s.guide.note = e.target.value; s.guide.reviewed = null; })} /></label>
    <TextLink onClick={() => { setSurface(null); openChat("guide"); }}>Ask Rumi to help phrase a question</TextLink><Action className="w-full" onClick={() => setReviewing(true)}>Review your visit guide</Action>
    {reviewing && <Card><Eyebrow>Patient review · {formatVisit(state.visit.at)} ET</Eyebrow><ol className="my-4 list-inside list-decimal space-y-3 text-sm">{state.guide.questions.map(q => <li key={q.id}>{q.text}</li>)}</ol>{state.logs.filter(l => state.guide.selectedLogIds.includes(l.id)).map(l => <p className="my-2 text-sm" key={l.id}>{l.at} · {l.kind}: {l.value}</p>)}<p className="my-3 whitespace-pre-wrap text-sm">{state.guide.note}</p><Note>No EHR delivery or clinician review is available.</Note><Action className="mt-4 w-full" disabled={!state.guide.questions.length && !state.guide.note && !state.guide.selectedLogIds.length} onClick={() => { if (commit(s => { s.guide.reviewed = guideFingerprint(s); })) setNotice("Visit guide saved as reviewed. Nothing was sent."); }}>{reviewed ? "Reviewed · saved" : "Save as reviewed"}</Action>{reviewed && <TextLink onClick={exportGuide}>Export reviewed text</TextLink>}</Card>}</>;
}

export function VisitWorkspace() {
  const { state, commit, setSurface } = usePrivia();
  const at = state.visitDraft || state.visit.at.slice(0, 16);
  const setAt = (value: string) => commit(s => { s.visitDraft = value; });
  const [review, setReview] = useState<boolean>(false);
  return <><Card><Eyebrow>Sample primary care · Elena</Eyebrow><h2 className="mt-2 font-fields text-2xl">{formatVisit(state.visit.at)} ET</h2><p className="my-3 text-sm">Sample practice<br />100 Example Lane, Demo City</p><Note>Fictional address. This demonstration does not establish an appointment with Privia.</Note><Row title="Your discussion guide" icon={<FileText size={20} />} onClick={() => setSurface("guide")} /><Row title="Lab preparation" icon={<CalendarDays size={20} />} onClick={() => setSurface("lab")} /></Card><details><summary className="min-h-11 cursor-pointer py-3 font-medium">Change the sample appointment</summary><div className="space-y-3"><label className="block space-y-2 text-sm"><span>New date and time · Eastern (September 2026)</span><input type="datetime-local" min="2026-09-17T00:00" max="2026-09-30T23:59" className={inputClass} value={at} onChange={e => { setAt(e.target.value); setReview(false); }} /></label><Action secondary onClick={() => setReview(true)} disabled={!at || !at.startsWith("2026-09-")}>Review change</Action>{review && <Card><p className="mb-3 text-sm">Change to {at.replace("T", " at ")} Eastern? Your questions stay; the guide and linked calendar event need another review.</p><Action onClick={() => { if (commit(s => { s.visit.at = `${at}:00-04:00`; s.visit.revision++; s.visitDraft = ""; s.lab.approval = null; s.guide.reviewed = null; })) setReview(false); }}>Apply sample change</Action></Card>}</div></details></>;
}
