import React from "react";
import { act, cleanup, fireEvent, render, renderHook, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { MemoryRouter } from "react-router-dom";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { applyLab, applyMessage, initialState, stateSchema, STORAGE_KEY, labFingerprint, messageFingerprint, guideFingerprint, labBlocker, outreachBlocker, quietNow, parseBP, channelCopy, type DemoState, type Turn } from "../privia/model";
import { buildContext, readTool, askRumi } from "../privia/ai";
import { PriviaProvider, usePrivia } from "../privia/store";
import { PriviaApp } from "../privia/PriviaApp";

beforeEach(() => { localStorage.clear(); HTMLElement.prototype.scrollIntoView = vi.fn(); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); });
const wrapper = ({ children }: { children: React.ReactNode }) => <QueryClientProvider client={new QueryClient({ defaultOptions: { mutations: { retry: false } } })}><MemoryRouter><PriviaProvider>{children}</PriviaProvider></MemoryRouter></QueryClientProvider>;
function prepared(): DemoState { const s = initialState(); s.aiConsent = true; s.sources = { gmail: true, calendar: true, records: true }; s.orderAvailable = true; s.lab.slot = "09:30"; s.lab.approval = labFingerprint(s); return s; }
function user(text: string): Turn { return { id: "u", role: "user", text, channel: "app", at: new Date().toISOString(), status: "complete", origin: "patient", dismissed: false }; }
function response(reply: string, extra: object = {}): Response { return new Response(JSON.stringify({ choices: [{ finish_reason: "tool_calls", message: { tool_calls: [{ id: "r", type: "function", function: { name: "respond", arguments: JSON.stringify({ reply, ...extra }) } }] } }] }), { status: 200 }); }

describe("Privia isolated domain and review gates", () => {
  it("rejects foreign patient snapshots instead of relabeling them", () => { expect(stateSchema.safeParse({ ...initialState(), patientId: "marcus" }).success).toBe(false); });
  it("does not read or mutate legacy storage", () => { localStorage.setItem("sano.web.v1", '{"profile":{"name":"Marcus"}}'); const { result } = renderHook(usePrivia, { wrapper }); act(() => { result.current.commit(s => { s.composer = "Elena draft"; }); }); expect(localStorage.getItem("sano.web.v1")).toContain("Marcus"); expect(result.current.state.composer).toBe("Elena draft"); });
  it("retains empty collections and unsent work through remount", () => { const one = renderHook(usePrivia, { wrapper }); act(() => one.result.current.commit(s => { s.logs = []; s.composer = "My draft"; s.guide.draftQuestion = "My question"; })); one.unmount(); const two = renderHook(usePrivia, { wrapper }); expect(two.result.current.state.logs).toEqual([]); expect(two.result.current.state.composer).toBe("My draft"); expect(two.result.current.state.guide.draftQuestion).toBe("My question"); });
  it("does not overwrite a damaged snapshot", () => { localStorage.setItem(STORAGE_KEY, "bad json"); const { result } = renderHook(usePrivia, { wrapper }); act(() => result.current.commit(s => { s.composer = "replace"; })); expect(localStorage.getItem(STORAGE_KEY)).toBe("bad json"); expect(result.current.error).toContain("not been replaced"); });
  it("a failed save leaves previous state and outcomes unchanged", () => { const { result } = renderHook(usePrivia, { wrapper }); vi.spyOn(Storage.prototype, "setItem").mockImplementation(() => { throw new Error("quota"); }); act(() => result.current.commit(s => { s.lab.message = "not saved"; })); expect(result.current.state.lab.message).toBe(""); expect(result.current.error).toContain("could not be saved"); });
  it("stops another tab overwriting newer work", () => { const { result } = renderHook(usePrivia, { wrapper }); act(() => window.dispatchEvent(new StorageEvent("storage", { key: STORAGE_KEY }))); act(() => result.current.commit(s => { s.composer = "stale"; })); expect(result.current.state.composer).toBe(""); expect(result.current.error).toContain("another tab"); });
  it("requires review, valid order and calendar permission", () => { const s = prepared(); s.lab.approval = null; expect(() => applyLab(s)).toThrow("Review"); s.orderAvailable = false; expect(labBlocker(s)).toContain("order"); s.sources.calendar = false; expect(labBlocker(s)).toContain("Reconnect"); });
  it("identifies the actual overlapping time", () => { const s = prepared(); s.lab.slot = "08:00"; expect(labBlocker(s)).toContain("overlaps"); });
  it("invalidates approval when the visit changes", () => { const s = prepared(); s.visit.revision++; expect(() => applyLab(s)).toThrow("changed"); });
  it("invalidates approval when source permission changes", () => { const s = prepared(); s.sources.gmail = false; expect(() => applyLab(s)).toThrow("changed"); });
  it("saves only a private-title calendar event, never a booking", () => { const s = applyLab(prepared()); expect(s.calendarEvents).toHaveLength(1); expect(s.calendarEvents[0].title).toBe("Personal appointment"); expect(JSON.stringify(s.calendarEvents)).not.toMatch(/diabetes|blood|faint|Example Lane/i); expect(s.messages).toHaveLength(0); expect(() => applyLab(s)).toThrow(); });
  it("message outcome is independent of the calendar outcome", () => { const s = prepared(); s.lab.message = "Could we discuss preparation?"; s.lab.messageApproval = messageFingerprint(s); const out = applyMessage(s, s.lab.messageApproval); expect(out.messages[0].status).toBe("Simulated · not sent"); expect(out.calendarEvents).toHaveLength(0); });
  it("editing recipient or text invalidates message review", () => { const s = prepared(); s.lab.message = "Question"; s.lab.messageApproval = messageFingerprint(s); const signature = s.lab.messageApproval; s.lab.recipient = "Other"; expect(() => applyMessage(s, signature)).toThrow(); });
  it("duplicate sample messages are blocked even after irrelevant source changes", () => { const s = prepared(); s.lab.message = "Question"; s.lab.messageApproval = messageFingerprint(s); const out = applyMessage(s, s.lab.messageApproval); out.sources.calendar = false; out.lab.messageApproval = messageFingerprint(out); expect(() => applyMessage(out, out.lab.messageApproval!)).toThrow("already"); });
  it("corrected selected observations invalidate guide review without deleting questions", () => { const s = prepared(); s.guide.questions = [{ id: "q", text: "My question" }]; s.guide.selectedLogIds = [s.logs[0].id]; s.guide.reviewed = guideFingerprint(s); s.logs[0].value = "135/82 mmHg"; expect(guideFingerprint(s)).not.toBe(s.guide.reviewed); expect(s.guide.questions[0].text).toBe("My question"); });
});

describe("permissions, memory and shared channels", () => {
  it("excludes clinical, inbox and calendar facts before AI consent to sources", () => { const context = JSON.stringify(buildContext(initialState())); expect(context).not.toMatch(/138\/84|200 Example Lane|HbA1c|Type 2 diabetes/); });
  it("read tools deny removed sources and fail unknown operations", () => { expect(readTool("search_sample_inbox", { query: "lab" }, initialState()).sources).toEqual([]); expect(readTool("compare_sample_calendar", {}, initialState()).sources).toEqual([]); expect(() => readTool("send_message", {}, prepared())).toThrow(); });
  it("searches actual sample content and compares conflicts", () => { expect(readTool("search_sample_inbox", { query: "location" }, prepared()).sources).toEqual(["lab-email"]); const data = readTool("compare_sample_calendar", {}, prepared()).data as { conflict: boolean }[]; expect(data.map(x => x.conflict)).toEqual([true, false, false]); });
  it("forgetting memory excludes its previous conversation from future requests", () => { const { result } = renderHook(usePrivia, { wrapper }); act(() => result.current.commit(s => { s.turns.push(user("I felt faint")); s.memories.push({ id: "m", text: "I felt faint", at: "now" }); })); act(() => result.current.privateEdit(s => { s.memories = []; })); expect(result.current.state.historyFrom).toBe(1); expect(JSON.stringify(buildContext(result.current.state))).not.toContain("felt faint"); });
  it("enabling a source preserves the ongoing conversation", () => { const { result } = renderHook(usePrivia, { wrapper }); act(() => result.current.commit(s => { s.turns.push(user("Please help")); })); act(() => result.current.privateEdit(s => { s.sources.gmail = true; })); expect(result.current.state.historyFrom).toBe(0); });
  it("requires two explicit pressure values and date/time", () => { expect(parseBP("138")).toBeNull(); expect(parseBP("138/84")).toBeNull(); expect(parseBP("BP 138/84 2026-09-17 08:00")?.value).toBe("138/84 mmHg"); expect(parseBP("12/600 2026-09-17 08:00")).toBeNull(); });
  it("SMS clarification and saving use one shared workspace without echoing values", () => { const { result } = renderHook(usePrivia, { wrapper }); act(() => result.current.sms("BP 138")); expect(result.current.state.logs).toHaveLength(1); expect(result.current.state.turns.at(-1)?.text).toBe(channelCopy.clarify); act(() => result.current.sms("BP 138/84 2026-09-17 08:00")); expect(result.current.state.logs).toHaveLength(2); expect(result.current.state.turns.at(-1)?.text).not.toContain("138"); act(() => result.current.sms("BP 138/84 2026-09-17 08:00")); expect(result.current.state.logs).toHaveLength(2); });
  it("STOP prevents both outreach channels without deleting care work", () => { const { result } = renderHook(usePrivia, { wrapper }); act(() => result.current.sms("STOP")); expect(result.current.state.channel.stopped).toBe(true); expect(result.current.state.channel.call).toBe(false); expect(result.current.state.logs).toHaveLength(1); });
  it("honors crossing-midnight quiet hours and a cross-channel frequency cap", () => { const s = prepared(); s.channel.sms = true; s.channel.call = true; expect(quietNow(s, 22)).toBe(true); expect(quietNow(s, 9)).toBe(false); expect(outreachBlocker(s, "sms", new Date("2026-09-17T14:00:00Z"))).toBeNull(); s.channel.lastOutreach = "2026-09-17T13:00:00Z"; expect(outreachBlocker(s, "call", new Date("2026-09-17T14:00:00Z"))).toContain("24 hours"); s.preferences.paused = true; expect(outreachBlocker(s, "sms", new Date())).toContain("paused"); });
});

describe("AI request ownership and direct UI", () => {
  it("blocks call continuation after STOP and requires a fresh verified session", () => { const fetcher = vi.spyOn(globalThis, "fetch"); const { result } = renderHook(usePrivia, { wrapper }); act(() => result.current.commit(s => { s.aiConsent = true; s.channel.call = true; })); act(() => result.current.setCallVerified(true)); act(() => result.current.sms("STOP")); act(() => result.current.send("Should not send", "call")); expect(fetcher).not.toHaveBeenCalled(); expect(result.current.notice).toContain("not verified"); });
  it("removed selected record is absent from future payloads", () => { const s = prepared(); s.excludedContextIds = ["visit", "order"]; expect(JSON.stringify(buildContext(s))).not.toContain("HbA1c"); expect(JSON.stringify(buildContext(s))).not.toContain("Type 2 diabetes"); });
  it("selected guide context includes the actual patient draft", () => { const s = prepared(); s.contextIds = ["guide"]; s.guide.draftQuestion = "Help me phrase this"; expect(JSON.stringify(buildContext(s))).toContain("Help me phrase this"); });
  it("reverting edited message text does not revive an old approval", () => { const { result } = renderHook(usePrivia, { wrapper }); act(() => result.current.commit(s => { s.lab.message = "A"; })); act(() => result.current.commit(s => { s.lab.messageApproval = messageFingerprint(s); })); act(() => result.current.commit(s => { s.lab.message = "B"; })); act(() => result.current.commit(s => { s.lab.message = "A"; })); expect(result.current.state.lab.messageApproval).toBeNull(); });
  it("rejects unread inbox citations even when Gmail is enabled", async () => { vi.spyOn(globalThis, "fetch").mockResolvedValue(response("Here", { suggestion: { kind: "surface", title: "Lab", text: "Plan", sourceIds: ["lab-email"], surface: "lab" } })); await expect(askRumi(prepared(), [user("Hi")], new AbortController().signal, vi.fn())).rejects.toThrow("unavailable evidence"); });
  it("unanswered question is recoverable after relaunch", async () => { vi.spyOn(globalThis, "fetch").mockResolvedValue(new Response("No", { status: 503 })); const first = renderHook(usePrivia, { wrapper }); act(() => first.result.current.commit(s => { s.aiConsent = true; })); act(() => first.result.current.send("Keep my question")); await waitFor(() => expect(first.result.current.isPending).toBe(false)); first.unmount(); const second = renderHook(usePrivia, { wrapper }); expect(second.result.current.state.pendingQuestion?.text).toBe("Keep my question"); });
  it("observation correction cancels old AI and excludes obsolete history", async () => { let finish: (v: Response) => void = () => {}; vi.spyOn(globalThis, "fetch").mockImplementation(() => new Promise(resolve => { finish = resolve; })); const { result } = renderHook(usePrivia, { wrapper }); act(() => result.current.commit(s => { s.aiConsent = true; })); act(() => result.current.send("Explain my old reading")); await waitFor(() => expect(result.current.isPending).toBe(true)); act(() => result.current.commit(s => { s.logs[0].value = "130/80 mmHg"; })); await act(async () => { finish(response("Old interpretation")); }); expect(result.current.state.turns).toHaveLength(1); expect(result.current.state.historyFrom).toBe(1); });
  it("includes the current question and does not send a browser secret header", async () => { const fetcher = vi.spyOn(globalThis, "fetch").mockResolvedValue(response("The supplied address is 200 Example Lane.")); const s = prepared(); await askRumi(s, [user("Only the address please")], new AbortController().signal, vi.fn()); const options = fetcher.mock.calls[0][1]!; expect(JSON.parse(options.body as string).messages.at(-1).content).toBe("Only the address please"); expect(options.headers).not.toHaveProperty("Authorization"); });
  it("does not call AI without consent", async () => { const fetcher = vi.spyOn(globalThis, "fetch"); await expect(askRumi(initialState(), [user("Hi")], new AbortController().signal, vi.fn())).rejects.toThrow("Enable"); expect(fetcher).not.toHaveBeenCalled(); });
  it("never fabricates a successful reply on failure", async () => { vi.spyOn(globalThis, "fetch").mockResolvedValue(new Response("unavailable", { status: 503 })); await expect(askRumi(prepared(), [user("Hi")], new AbortController().signal, vi.fn())).rejects.toThrow("could not connect"); });
  it("rejects truncated responses and invented source references", async () => { const mock = vi.spyOn(globalThis, "fetch").mockResolvedValue(new Response(JSON.stringify({ choices: [{ finish_reason: "length", message: {} }] }))); await expect(askRumi(prepared(), [user("Hi")], new AbortController().signal, vi.fn())).rejects.toThrow("incomplete"); mock.mockResolvedValue(response("Here", { suggestion: { kind: "surface", title: "Lab", text: "Plan", sourceIds: ["wrong-patient"], surface: "lab" } })); await expect(askRumi(prepared(), [user("Hi")], new AbortController().signal, vi.fn())).rejects.toThrow("unavailable evidence"); });
  it("suppresses proposals during a patient pause", async () => { vi.spyOn(globalThis, "fetch").mockResolvedValue(response("We can leave it there.", { suggestion: { kind: "question", title: "Question", text: "Why", sourceIds: [] } })); const s = prepared(); s.preferences.paused = true; expect((await askRumi(s, [user("Not now")], new AbortController().signal, vi.fn())).suggestion).toBeUndefined(); });
  it("cancellation ignores even a late successful network response", async () => { let finish: (v: Response) => void = () => {}; vi.spyOn(globalThis, "fetch").mockImplementation(() => new Promise(resolve => { finish = resolve; })); const { result } = renderHook(usePrivia, { wrapper }); act(() => result.current.commit(s => { s.aiConsent = true; })); act(() => result.current.send("Do not lose this")); await waitFor(() => expect(result.current.isPending).toBe(true)); act(() => result.current.stop()); await act(async () => { finish(response("late reply")); }); expect(result.current.state.turns).toHaveLength(1); expect(result.current.state.turns[0].text).toBe("Do not lose this"); });
  it("Log is a sheet between four destinations, not a fifth destination", () => { render(<PriviaApp />, { wrapper }); expect(screen.getByRole("navigation", { name: "Main navigation" }).querySelectorAll("a")).toHaveLength(4); fireEvent.click(screen.getByRole("button", { name: "Log" })); expect(screen.getByRole("dialog")).toBeInTheDocument(); expect(screen.getByLabelText("Blood pressure · mmHg")).toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Enable temporary AI" })).not.toBeInTheDocument(); });
  it("guide question composer survives closing and reopening", () => { render(<PriviaApp />, { wrapper }); fireEvent.click(screen.getByRole("button", { name: /Prepare in your own words/ })); fireEvent.change(screen.getByLabelText("Add a question"), { target: { value: "My unfinished question" } }); fireEvent.click(screen.getByRole("button", { name: "Close" })); fireEvent.click(screen.getByRole("button", { name: /Prepare in your own words/ })); expect(screen.getByLabelText("Add a question")).toHaveValue("My unfinished question"); });
});
